// Crypto API Service Types
export interface CryptocurrencyData {
  symbol: string;
  name: string;
  price: number;
  change: number;
  marketCap: number;
  volume: number;
}

export interface CryptoApiService {
  name: string;
  fetchInitialData: (symbols: string[]) => Promise<CryptocurrencyData[]>;
  setupWebSocket?: (symbols: string[], onUpdate: (data: CryptocurrencyData) => void) => WebSocket | null;
  supportsWebSocket: boolean;
}

// Crypto symbol to name mapping
export const cryptoNames: { [key: string]: string } = {
  'BTC': 'Bitcoin',
  'ETH': 'Ethereum', 
  'BNB': 'BNB',
  'SOL': 'Solana',
  'XRP': 'XRP',
  'DOGE': 'Dogecoin',
  'ADA': 'Cardano',
  'TRX': 'TRON',
  'AVAX': 'Avalanche',
  'SHIB': 'Shiba Inu',
  'DOT': 'Polkadot',
  'LINK': 'Chainlink',
  'BCH': 'Bitcoin Cash',
  'NEAR': 'NEAR Protocol',
  'MATIC': 'Polygon',
  'ICP': 'Internet Computer',
  'UNI': 'Uniswap',
  'LTC': 'Litecoin',
  'XLM': 'Stellar',
  'ETC': 'Ethereum Classic',
  'ATOM': 'Cosmos',
  'HBAR': 'Hedera',
  'FIL': 'Filecoin',
  'APT': 'Aptos',
  'LDO': 'Lido DAO',
  'VET': 'VeChain',
  'ARB': 'Arbitrum',
  'TAO': 'Bittensor',
  'MNT': 'Mantle',
  'IMX': 'Immutable X',
  'INJ': 'Injective',
  'OP': 'Optimism',
  'RENDER': 'Render Token',
  'SEI': 'Sei',
  'WIF': 'dogwifhat',
  'STX': 'Stacks',
  'SUI': 'Sui',
  'AAVE': 'Aave',
  'GRT': 'The Graph',
  'THETA': 'Theta Network',
  'RUNE': 'THORChain',
  'FTM': 'Fantom',
  'BONK': 'Bonk',
  'PEPE': 'Pepe',
  'ALGO': 'Algorand',
  'FLOW': 'Flow',
  'EGLD': 'MultiversX',
  'MANA': 'Decentraland',
  'SAND': 'The Sandbox',
  'XTZ': 'Tezos',
  'BEAM': 'Beam',
  'AXS': 'Axie Infinity',
  'CHZ': 'Chiliz',
  'DYDX': 'dYdX',
  'KAS': 'Kaspa',
  'ROSE': 'Oasis Network',
  'GALA': 'Gala',
  'ENS': 'Ethereum Name Service',
  'BLUR': 'Blur',
  'GMT': 'STEPN',
  'CFX': 'Conflux',
  'CRV': 'Curve DAO Token',
  'ORDI': 'ORDI',
  'COMP': 'Compound',
  'PYTH': 'Pyth Network',
  'SUPER': 'SuperVerse',
  'WLD': 'Worldcoin',
  'SATS': '1000SATS',
  'PENDLE': 'Pendle',
  'FET': 'Fetch.ai',
  'JASMY': 'JasmyCoin',
  'OCEAN': 'Ocean Protocol',
  'JTO': 'Jito',
  'CAKE': 'PancakeSwap',
  'TIA': 'Celestia',
  'JUP': 'Jupiter',
  'STRK': 'Starknet',
  'MEME': 'Memecoin',
  'BOME': 'BOOK OF MEME',
  'ENA': 'Ethena',
  'WOO': 'WOO Network',
  'RNDR': 'Render Token',
  'FLOKI': 'FLOKI',
  'PEOPLE': 'ConstitutionDAO',
  'AGIX': 'SingularityNET',
  'ARKM': 'Arkham',
  'KAVA': 'Kava',
  'WAVES': 'Waves',
  'ZIL': 'Zilliqa',
  'AR': 'Arweave',
  'LUNC': 'Terra Luna Classic',
  'ONE': 'Harmony',
  'QTUM': 'Qtum',
  'ZEC': 'Zcash',
  'DASH': 'Dash',
  'NEO': 'Neo',
  'IOST': 'IOST',
  'ZEN': 'Horizen',
  'TFUEL': 'Theta Fuel',
  'IOTX': 'IoTeX'
};
